### ISSUE TITLE
Add About Us page using front-end

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#20]
Please follow the provided guidelines and contribute accordingly.

**Comment by Chanchal14-creator** [comment]
I want to work on this issue pease give me brief description what do you want in this, either a sample which can be used anywhere or you want something else to be displayed.

**Comment by Chanchal14-creator** [comment]
okey then please assign me this issue i want to work on this.

**Comment by Slytherin33** [comment]
Great up @Divyam-Deep, task completed as per requirements.
