### ISSUE TITLE
Create sample portfolio page using front-end

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#21]
Please follow the provided guidelines and contribute accordingly.

**Comment by AaryanSingh0017** [comment]
Plz assign me this.

**Comment by Slytherin33** [comment]
ok you both can go ahead with this.

**Comment by Slytherin33** [comment]
Good portfolio page for beginners' understanding. Great work.

**Comment by Harshit-tech76** [comment]
Thank you.
