### ISSUE TITLE
Create A simple dice game website

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#23]
Please follow the provided guidelines and contribute accordingly.

**Comment by Divyam-Deep** [comment]
i can help you with that

**Comment by Soumyajit2825** [comment]
@Slytherin33 want to contribute also

**Comment by Harshit-tech76** [comment]
Highly interested. Please assign me this.

**Comment by Slytherin33** [comment]
@Harshit-tech76 you are assigned this issue.

**Comment by Slytherin33** [comment]
Perfect website as required. Great job.

**Comment by Harshit-tech76** [comment]
Thanks a lot.
