### ISSUE TITLE
Add JavaScript cheatsheet

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#3]
Please follow the provided guidelines and contribute accordingly.

**Comment by Harshit-tech76** [comment]
I'd like to work on this. Can you please assign it to me?

**Comment by Slytherin33** [comment]
ok @Harshit-tech76 go ahead.

**Comment by Soumyajit2825** [comment]
@Slytherin33 ok PR done. Please Check

**Comment by Soumyajit2825** [comment]
@Slytherin33 Yeah I have done it now

**Comment by Slytherin33** [comment]
Best documentation for JavaScript Beginners. Great job.

**Comment by Soumyajit2825** [comment]
thank you so much
