### ISSUE TITLE
Create basic footer using html and css

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#45]
Please follow the provided guidelines and contribute accordingly.

**Comment by Nevilkumar** [comment]
Hi @Slytherin33 , I would like to work on this issue. Please assign it to me.

**Comment by hash143** [comment]
Please assign me this task.

**Comment by Slytherin33** [comment]
Ok you both are assigned this task.

**Comment by Nevilkumar** [comment]
@Slytherin33 Can You please review and merge the PR https://github.com/Slytherin33/WebCollections/pull/50 .
