### ISSUE TITLE
Add sample ecommerce page

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#7]
Please follow the provided guidelines and contribute accordingly.

**Comment by Harshit-tech76** [comment]
Can I work on this task?

**Comment by Slytherin33** [comment]
ok @Harshit-tech76 you are good to go.

**Comment by Slytherin33** [comment]
It would be great if it is online game selling website.

**Comment by Slytherin33** [comment]
Good website page. Nice work.

**Comment by Harshit-tech76** [comment]
Thanks a lot.
