### ISSUE TITLE
Add sample 404 error page

### ISSUE THREAD

**Issue by Slytherin33** [Slytherin33/WebCollections#9]
Please follow the provided guidelines and contribute accordingly.

**Comment by Harshit-tech76** [comment]
Highly interested in this, please assign it to me.

**Comment by Slytherin33** [comment]
ok @Harshit-tech76 you are assigned.

**Comment by Slytherin33** [comment]
Good work. Perfect page.

**Comment by Harshit-tech76** [comment]
Thanks a lot.
